### ISSUE TITLE
MSVC Support

### ISSUE THREAD

**Issue by tresf** [java-native/java-simple-serial-connector#2]
@woodrowbarlow I'd like to make the following patches to provide support for MSVC compiler:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ce5e05e..8c54ea1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,6 +1,7 @@
 cmake_minimum_required(VERSION 3.9)
 project(jssc VERSION 2.8.0 DESCRIPTION "Java Simple Serial Connector")

+find_package(Java)
 find_package(JNI)

 if(APPLE)
diff --git a/src/cpp/windows/jssc.cpp b/src/cpp/windows/jssc.cpp
index 08428de..92dc1bb 100644
--- a/src/cpp/windows/jssc.cpp
+++ b/src/cpp/windows/jssc.cpp
@@ -46,7 +46,7 @@ JNIEXPORT jlong JNICALL Java_jssc_SerialNativeInterface_openPort(JNIEnv *env, jo
     const char* port = env->GetStringUTFChars(portName, JNI_FALSE);

     //since 2.1.0 -> string concat fix
-    char portFullName[strlen(prefix) + strlen(port) + 1];
+    char* portFullName = (char *)malloc(strlen(prefix) + strlen(port) + 1);
     strcpy(portFullName, prefix);
     strcat(portFullName, port);
     //<- since 2.1.0
@@ -259,7 +259,7 @@ JNIEXPORT jbyteArray JNICALL Java_jssc_SerialNativeInterface_readBytes
     DWORD lpNumberOfBytesTransferred;
     DWORD lpNumberOfBytesRead;
     OVERLAPPED *overlapped = new OVERLAPPED();
-    jbyte lpBuffer[byteCount];
+    jbyte * lpBuffer = (jbyte *)malloc(byteCount);
     jbyteArray returnArray = env->NewByteArray(byteCount);
     overlapped->hEvent = CreateEventA(NULL, true, false, NULL);
     if(ReadFile(hComm, lpBuffer, (DWORD)byteCount, &lpNumberOfBytesRead, overlapped)){
```

**Comment by woodrowbarlow** [comment]
it looks like this would leak memory. am i missing something?

**Comment by tresf** [comment]
> it looks like this would leak memory. am i missing something?

MSVC doesn't support VLAs.  Is there a better way?  Should we just allocate a larger arraY?

**Comment by tresf** [comment]
Reference: https://stackoverflow.com/questions/5246900/enabling-vlas-variable-length-arrays-in-ms-visual-c

**Comment by woodrowbarlow** [comment]
oh, i see. but the patch as you've posted it would leak memory because the memory isn't freed.

i would like to see us generate our first release build before we change the code at all, wherever possible. our release binaries for windows will be cross-compiled via mingw, so MSVC support isn't needed for our first release.

**Comment by tresf** [comment]
> i would like to see us generate our first release build before we change the code at all, wherever possible.

The above areas are the only changes required.  Please reconsider as it allows MSVC out of the gate, which will attract new developers.

> our release binaries for windows will be cross-compiled via mingw, so MSVC support isn't needed for our first release.

I've already written the mingw stuff on the temporary `cmake` branch, so I'm well aware, but 50% of developers use Windows.  This could yield more PRs and fixes.  I'd like to launch with it.

**Comment by woodrowbarlow** [comment]
> The above areas are the only changes required.

and yet i see multiple bugs: leaking memory and assumption that a jbyte pointer is 1 byte. from a performance standpoint, it's also a little cavalier to promote a stack allocation to a heap allocation in the read callback (the most performance-critical part of the code).

my point is not that your code has bugs, but that all code has bugs and we should release a version that just has the current, known issues.

i'm not against MSVC support, i'm just asking that we hold off until after the first release. for the (very brief) time-being, windows users have bash and can run the exact same toolchain as the linux users. i don't think "attracting developers" is a concern right now -- we'd want to have contribution guidelines and a code review process first anyway.

we're likely to discover that a larger-scoped change, like maybe targeting a c90 compiler rather than a c99 C++ compiler, will make it work smoothly with not just MSVC, but also a litany of other compilers that aren't currently supported.

**Comment by woodrowbarlow** [comment]
i should say, i know i can be a little "loud" with my opinions.
but what i'm sharing here is just my opinion. your opinion is valid too and if you choose to move forward with your patch, that's okay with me.
but please free the memory before the function returns.

**Comment by tresf** [comment]
> and yet i see multiple bugs: leaking memory and assumption that a jbyte pointer is 1 byte. from a performance standpoint, it's also a little cavalier to promote a stack allocation to a heap allocation in the read callback (the most performance-critical part of the code).

 Can you propose the sane, fixed length instead?  If you're that worried we can rep in a pre-compiler check.

> we're likely to discover that a larger-scoped change, like maybe targeting a c90 compiler rather than a c99 C++ compiler, will make it work smoothly with not just MSVC, but also a litany of other compilers that aren't currently supported.

Agreed but 50% of developers use Windows.  I'm not asking about an education or a minority support here.

**Comment by woodrowbarlow** [comment]
okay, i'll make a PR onto the cmake branch using fixed-length buffers.
