### ISSUE TITLE
[RFE] (for later): Add mvnw wrapper scripts

### ISSUE THREAD

**Issue by bmhm** [java-native/java-simple-serial-connector#27]
Suggestion for later:

Add https://github.com/takari/maven-wrapper

It will put two small scripts (`mvnw` (sh) and `mvnw.bat`) into our repository, as well as a folder `.mvnw` containing a single tiny tiny jar file.

Benefit:
 * Non-Maven-Users do not need to install maven
 * Just executing `./mvnw clean install` or just `./mvnw` will suffice. If maven is not installed locally, `mvnw` will download it.
  * Commonly used

Drawbacks:
  * Binary files in repo (but they don't change often and are tiny)

**Comment by tresf** [comment]
I vote against this because we need `cmake` anyway.  Sure, you can try to grab `cmake` for the current platform using yet another plugin, but I feel the build system is simple and clean currently.  The strongest argument for this I feel is version management, but the project itself leads with the following statement:

> Maven to date has been very stable for users, is available on most systems or is easy to procure

This is my experience with Maven as well.  Note, macOS 10.8 did fail with the built-in `maven` command, but Homebrew grabbed me a new one and it wasn't too hard to workaround for an unsupported OS.

So far I've built JSSC on:
- Ubuntu 14.04
- Ubuntu 16.04
- Windows 10 + MSVC
- macOS 10.14
- macOS 10.8 (using `maven` from Homebrew)

I don't yet find this experience lacking a helper script.

@bmhm which scenario did you run into where `mvnw` made this easier?  Was it the Pi?

**Comment by bmhm** [comment]
The best I came up with was also taken from their github README:

> but with many of the recent changes in Maven it will be easier for users to have a fully encapsulated build setup provided by the project. 

Meaning: It is (almost) self-contained. If this is not a goal and not needed, I agree, skip this as `won’t fix`.

> With the Maven Wrapper this is very easy to do and it's a great idea borrowed from Gradle.

Gradle’s best argument is to provide a reliable and stable build.

---

I think in the end they created `gradlew` for better acceptance. This is probably not needed, as you already pointed out and cited from the plugin’s README.

I'll close this as `won’tfix` then. It is good to have this decision documented. :-)
